language: node_js
node_js:
  - "4.1"

services:
  - mongodb

scripts: {
  "start": "node app.js",
  "test": "mocha"
}

# deploy:
#   app:
#   provider: heroku
#   api_key:
#     secure: 166f0b6348fdccde864dc9aecb3d50bb
